### ISSUE TITLE
Source and Receiver positions

### ISSUE THREAD

**Issue by gladys0313** [DavidDiazGuerra/gpuRIR#12]
Hello! Thanks for this very cool tool! I have a little question regarding the definition of the sound source and receiver positions. What is the coordinate origin that the source and receiver positions are with respect to? 
I tried a **room size** of [**3**, 3, 2.5], a **source** position of [**2**, 2.9, 0.5], and a **receiver** position of [**-2**, 1, 0.5]. I thought there would be error in the simulation because the distance between the source and the receiver along the x-axis is 2-(-2) = 4, which is even larger than the room size in x direction, but the simulation still ran successfully and output a RIR which looks normal. 
I'm a bit confused about this.. Is this a little error in the code? (__init__.py, line 142, line 143) 
Thanks in advance.

**Comment by DavidDiazGuerra** [comment]
Hello! The point `[0, 0, 0]` is one corner of the room and `[room_sz[0], room_sz[1], room_sz[2]]` is the farthest one. Therefore, a receiver in `[-2, 1, 0.5]` would be outside the room no matter the position of the source (and even the size of the room) due to the negative x coordinate.

I've modified [init.py, line 142, line 143](https://github.com/DavidDiazGuerra/gpuRIR/blob/c2e7f6e5591757b959d766f92609a4f04d920562/gpuRIR/__init__.py#L142-L143) so it also breaks checks that there are no negative coordinates; see 2456725.

I hope it answered your questions.
