### ISSUE TITLE
Best way to simulate a random rirs?

### ISSUE THREAD

**Issue by LearnedVector** [DavidDiazGuerra/gpuRIR#21]
Whats the best way to simulate random rirs?

**Comment by DavidDiazGuerra** [comment]
The library doesn't include an option to generate random trajectories, but you can use [Python's `random` library](https://docs.python.org/3/library/random.html) to get random values for the room size, source and receiver position, and reverberation time and then use gpuRIR to compute a RIR from them.

I have a class [here](https://github.com/DavidDiazGuerra/Cross3D/blob/a5bc9e08ca899e7738f5f1067dd0d81c7dc0232c/acousticTrackingDataset.py#L590) with a Pytorch dataset that generates random RIRs, but the code is a bit messy since it wasn't supposed to be a public library.

**Comment by LearnedVector** [comment]
got it. thanks!
