### ISSUE TITLE
A problem occured when do simulation

### ISSUE THREAD

**Issue by lsg1213** [DavidDiazGuerra/gpuRIR#29]
https://github.com/DavidDiazGuerra/gpuRIR/blob/master/examples/time_vs_T60.py#L39
When execute above line, an error message is occured
GPUassert: an illegal memory access was encountered /tmp/pip-req-build-y9g99fpi/src/gpuRIR_cuda.cu 822

My environment is CUDA=11.4, UBUNTU 18.04, python=3.7.12, gpu is titan rtx

please help me

**Comment by lsg1213** [comment]
However, a weird thing is that https://github.com/DavidDiazGuerra/gpuRIR/blob/master/examples/example.py is executing well.

**Comment by DavidDiazGuerra** [comment]
Are you executing the time_vs_T60.py script as it is without any modifications? Do you know in which iteration (the values of `i` and `j`) the program crashed?

**Comment by lsg1213** [comment]
Yes I didn't modificate it except CUDA_VISIBLE_DEVICES=gpunumber
and i=0, j=0 crashed

**Comment by DavidDiazGuerra** [comment]
Sorry for the late reply. It seems like the last commit introduced some kind of bug. I'll try to fix it in the following days, as a workaround till then, you can install the previous version of the library with:

```
pip uninstall gpuRIR
pip install https://github.com/DavidDiazGuerra/gpuRIR/zipball/57463ffe3dd16e2bb10b9624b044e8216a956018
```

**Comment by DavidDiazGuerra** [comment]
93b52e5367b4578e977388a83e144d565e65c1fd had a bug concerning the shared memory reservation for the orientation of the speakers, but it should be fixed now with the last commit. However, this increases the shared memory consumption and therefore reduces the maximum number of RIRs that can be computed in parallel. I'll try to modify the kernel so the orientation of the source/receivers is not copied to shared memory in the case of omnidirectional directivity patterns.

I'm closing the issue now since it should be already fixed, but let me know if you still get that error.
